#!/usr/bin/env node
require('dotenv').config()
const crypto = require('crypto')
const { program } = require('commander')
const jsonfile = require('jsonfile')
const { encrypt } = require('./lib/crypto-helper')
const bcrypt = require('bcryptjs')
const chalk = require('chalk')

const { DATA_STORE } = process.env

const secretsFilePath = DATA_STORE // Adjust the path as necessary

program.version('1.0.0', '-v, --version')
  .description('CLI tool for managing encryption keys and applications within a keystore.')

/**
 * User Management
 */
const addUser = (username, password, apps) => {
  const file = DATA_STORE
  const db = jsonfile.readFileSync(file)

  if (db._users && db._users[username]) {
    console.error(`User ${chalk.red(username)} already exists`)
    return
  }

  const hashedPassword = bcrypt.hashSync(password, 10)
  db._users = db._users || {}
  db._users[username] = { password: hashedPassword, apps }

  jsonfile.writeFileSync(file, db)
  console.log(`User ${chalk.green(username)} added successfully`)
}

const delUser = (username) => {
  const file = DATA_STORE
  const db = jsonfile.readFileSync(file)

  if (!db._users || !db._users[username]) {
    console.error(`User ${chalk.red(username)} not found`)
    return
  }

  delete db._users[username]
  jsonfile.writeFileSync(file, db)
  console.log(`User ${chalk.red(username)} deleted successfully`)
}

const updateUserPassword = (username, newPassword) => {
  const file = DATA_STORE
  const db = jsonfile.readFileSync(file)

  if (!db._users || !db._users[username]) {
    console.error(`User ${chalk.red(username)} not found`)
    return
  }

  const hashedPassword = bcrypt.hashSync(newPassword, 10)
  db._users[username].password = hashedPassword
  jsonfile.writeFileSync(file, db)
  console.log(`Password updated successfully for ${chalk.green(username)}`)
}

const listUserAccess = (username) => {
  const db = jsonfile.readFileSync(secretsFilePath)
  if (!db._users || !db._users[username]) {
    console.error(`User ${chalk.red(username)} not found`)
    return
  }

  console.log(`User ${chalk.green(username)} has access to the following applications:`)
  db._users[username].apps.forEach(appGuid => {
    if (db[appGuid]) {
      console.log(`- ${chalk.cyan(db[appGuid].name)} (GUID: ${chalk.yellow(appGuid)}})`)
    } else {
      console.log(`- Application not found for GUID: ${chalk.red(appGuid)}}`)
    }
  })
}

const addUserAccess = (username, app) => {
  const db = jsonfile.readFileSync(DATA_STORE)
  if (!db._users || !db._users[username]) {
    console.log(`User ${chalk.red(username)} not found`)
    return
  }
  if (!db._users[username].apps.includes(app)) {
    db._users[username].apps.push(app)
    jsonfile.writeFileSync(DATA_STORE, db)
    console.log(`Access to ${chalk.cyan(app)} added for user ${chalk.green(username)}`)
  } else {
    console.log(`User ${chalk.green(username)} already has access to ${chalk.cyan(app)}`)
  }
}

const deleteUserAccess = (username, app) => {
  const db = jsonfile.readFileSync(DATA_STORE)
  if (!db._users || !db._users[username]) {
    console.log(`User ${chalk.green(username)} not found`)
    return
  }
  const index = db._users[username].apps.indexOf(app)
  if (index > -1) {
    db._users[username].apps.splice(index, 1)
    jsonfile.writeFileSync(DATA_STORE, db)
    console.log(`Access to ${chalk.red(app)} removed for user ${chalk.green(username)}`)
  } else {
    console.log(`User ${chalk.green(username)} does not have access to ${chalk.cyan(app)}`)
  }
}

const listUsers = () => {
  const db = jsonfile.readFileSync(secretsFilePath)
  if (!db._users || Object.keys(db._users).length === 0) {
    console.log(chalk.yellow('No users found.'))
    return
  }

  console.log(chalk.green('Users:'))
  Object.entries(db._users).forEach(([username, userDetail]) => {
    console.log(`  - ${chalk.cyan(username)}`)
  })
}

/**
 * End User Management
 */

const ignoreApp = (key) => {
  const ignoreList = ['_users']
  return ignoreList.includes(key)
}

// List all applications
const listApplications = () => {
  jsonfile.readFile(secretsFilePath, (err, obj) => {
    if (err) return console.error(err)
    console.log('Applications:')
    Object.entries(obj).forEach(([guid, appDetails]) => {
      if (guid !== '_users') {
        console.log(`  - ${chalk.green(appDetails.name)} (GUID: ${chalk.yellow(guid)})`)
      }
    })
  })
}

// List all keys
const listAllKeys = (appName) => {
  if (ignoreApp(appName)) {
    console.error('invalid application name')
    return
  }
  jsonfile.readFile(secretsFilePath, (err, obj) => {
    if (err) return console.error(err)
    const appGuid = Object.keys(obj).find(key => obj[key].name === appName)
    if (!appGuid) {
      console.error(`Application ${chalk.red(appName)} not found`)
      return
    }
    console.log('Keys:')
    Object.keys(obj[appGuid].keys).forEach(key => {
      console.log(`  - ${chalk.yellow(key)}`)
    })
  })
}

// Add a new application
const addApplication = (appName) => {
  if (ignoreApp(appName)) {
    console.error(`invalid ${chalk.red(appName)} application name`)
    return
  }
  const appGuid = crypto.randomUUID()
  const newApp = {
    [appGuid]: { name: appName, keys: {} }
  }
  jsonfile.readFile(secretsFilePath, (err, obj) => {
    if (err) return console.error(err)
    obj = { ...obj, ...newApp }
    jsonfile.writeFile(secretsFilePath, obj, (err) => {
      if (err) console.error(err)
      console.log(`Added new application: ${chalk.cyan(appName)} (GUID: ${chalk.yellow(appGuid)})`)
    })
  })
}

// Add or update a key for an application
const addOrUpdateKey = (appName, keyName, value) => {
  if (ignoreApp(appName)) {
    console.error(`invalid application name ${chalk.red(appName)}`)
    return
  }
  jsonfile.readFile(secretsFilePath, (err, obj) => {
    if (err) return console.error(err)
    const appEntry = Object.entries(obj).find(([_, details]) => details.name === appName)
    if (!appEntry) {
      console.error(`Application ${chalk.red(appName)} not found`)
      return
    }
    const [appDetails] = appEntry
    appDetails.keys[keyName] = encrypt(value) // Encrypt the value before storing
    jsonfile.writeFile(secretsFilePath, obj, (err) => {
      if (err) console.error(err)
      console.log(`Key '${chalk.cyan(keyName)}' updated for application '${chalk.cyan(appName)}'.`)
    })
  })
}

// Subcommand to delete an application
const deleteApplication = (appName) => {
  if (ignoreApp(appName)) {
    console.error(`invalid ${chalk.red(appName)} application name`)
    return
  }
  jsonfile.readFile(secretsFilePath, (err, obj) => {
    if (err) return console.error(err)
    const appGuid = Object.keys(obj).find(key => obj[key].name === appName)
    if (!appGuid) {
      console.error(`Application ${chalk.red(appName)} not found`)
      return
    }
    delete obj[appGuid]
    jsonfile.writeFile(secretsFilePath, obj, (err) => {
      if (err) console.error(err)
      console.log(`Application '${chalk.cyan(appName)}' deleted.`)
    })
  })
}

// Subcommand to delete a key from an application
const deleteKey = (appName, keyName) => {
  if (ignoreApp(appName)) {
    console.error(`invalid ${chalk.red(appName)} application name`)
    return
  }
  jsonfile.readFile(secretsFilePath, (err, obj) => {
    if (err) return console.error(err)
    const appGuid = Object.keys(obj).find(key => obj[key].name === appName)
    if (!appGuid) {
      console.error(`Application ${chalk.red(appName)} not found`)
      return
    }
    if (obj[appGuid].keys[keyName]) {
      delete obj[appGuid].keys[keyName]
      jsonfile.writeFile(secretsFilePath, obj, (err) => {
        if (err) console.error(err)
        console.log(`Key '${chalk.red(keyName)}' deleted from '${chalk.cyan(appName)}'.`)
      })
    } else {
      console.log(`Key "${chalk.red(keyName)}" not found.`)
    }
  })
}

// Define commands with detailed descriptions
program
  .command('listkeys <app_name>')
  .description('list all keys for a given application')
  .action(listAllKeys)

program
  .command('addkey <app_name> <key_name> <value>')
  .description('add or update a key for a specified application')
  .action(addOrUpdateKey)

program
  .command('delkey <app_name> <key_name>')
  .description('delete a specified key from an application')
  .action(deleteKey)

program
  .command('listapps')
  .description(' list all applications and their app codes')
  .action(listApplications)

program
  .command('addapp <app_name>')
  .description('add a new application with a unique GUID')
  .action(addApplication)

program
  .command('delapp <app_name>')
  .description('delete a specified application by name')
  .action(deleteApplication)

program
  .command('listusers')
  .description(' list all users and their application access')
  .action(listUsers)

program
  .command('adduser <username> <password> <apps...>')
  .description('add a new user with access to specified app keys')
  .action(addUser)
  .on('--help', () => {
    console.log('')
    console.log('Example:')
    console.log('  $ keystore.js adduser john doe123 app1 app2')
  })

program
  .command('deluser <username>')
  .description('delete a user')
  .action(delUser)

program
  .command('userpwd <username> <newPassword>')
  .description('set or reset a user password')
  .action(updateUserPassword)

program
  .command('listaccess <username>')
  .description('list all applications a user has access to')
  .action(listUserAccess)

program
  .command('addaccess <username> <app>')
  .description(' add application access for a user')
  .action((username, app) => addUserAccess(username, app))

program
  .command('delaccess <username> <app>')
  .description('delete application access for a user')
  .action((username, app) => deleteUserAccess(username, app))

program.parse(process.argv)
